apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dew-org-ingress
  labels:
    name: dew-org-ingress
spec:
  defaultBackend:
    service:
      name: deworg-gateway
      port:
        number: 80
  rules:
    - host: api.deworg.com
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: deworg-gateway
                port:
                  number: 80
