global:
  name: consul
  datacenter: dewdc1
server:
  replicas: 2
ui:
  enabled: true
  service:
    type: LoadBalancer
connectInject:
  enabled: true
controller:
  enabled: true
dns:
  enabled: true
  enableRedirection: true
