apiVersion: v1
kind: ServiceAccount
metadata:
  name: deworg-invoices
---
apiVersion: v1
kind: Service
metadata:
  name: deworg-invoices
spec:
  selector:
    app: deworg-invoices
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deworg-invoices
  annotations:
    "consul.hashicorp.com/connect-inject": "true"
spec:
  selector:
    matchLabels:
      app: deworg-invoices
  template:
    metadata:
      labels:
        app: deworg-invoices
    spec:
      containers:
        - name: deworg-invoices
          image: deworg/invoices:0.1.0
          env:
            - name: CONSUL_HOST
              value: "consul-server.consul"
            - name: AUTH0_AUDIENCE
              valueFrom:
                configMapKeyRef:
                  name: auth0
                  key: audience
            - name: AUTH0_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: auth0
                  key: domain
          ports:
            - containerPort: 8080
