apiVersion: v1
kind: ServiceAccount
metadata:
  name: deworg-products
---
apiVersion: v1
kind: Service
metadata:
  name: deworg-products
spec:
  selector:
    app: deworg-products
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deworg-products
  annotations:
    "consul.hashicorp.com/connect-inject": "true"
spec:
  selector:
    matchLabels:
      app: deworg-products
  template:
    metadata:
      labels:
        app: deworg-products
    spec:
      containers:
        - name: deworg-products
          image: deworg/products:0.1
          env:
            - name: CONSUL_HOST
              value: "consul-server.consul"
            - name: CONSUL_PORT
              value: "8500"
            - name: MONGO_HOST
              value: deworg-db
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
