apiVersion: v1
kind: ServiceAccount
metadata:
  name: deworg-db
---
kind: Service
apiVersion: v1
metadata:
  name: deworg-db
spec:
  selector:
    app: deworg-db
  ports:
    - port: 27017
      targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deworg-db
spec:
  selector:
    matchLabels:
      app: deworg-db
  template:
    metadata:
      labels:
        app: deworg-db
    spec:
      containers:
      - name: deworg-db
        image: mongo
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 27017
        volumeMounts:
          - name: deworg-db-data
            mountPath: /data/db
      volumes:
        - name: deworg-db-data
          persistentVolumeClaim:
            claimName: deworg-data-claim



