controller:
  containerEnv:
    - name: PROJECT_ID
      valueFrom:
        secretKeyRef:
          name: jenkins-k8s-config
          key: project_id
    - name: GITHUB_REPO
      valueFrom:
        secretKeyRef:
          name: github-secrets
          key: github_repo
    - name: GITHUB_USERNAME
      valueFrom:
        secretKeyRef:
          name: github-secrets
          key: github_username
    - name: GITHUB_TOKEN
      valueFrom:
        secretKeyRef:
          name: github-secrets
          key: github_token
    - name: jenkins_tf_ksa
      valueFrom:
        secretKeyRef:
          name: jenkins-k8s-config
          key: jenkins_tf_ksa
  servicePort: 80
  serviceType: LoadBalancer
  installPlugins:
    - blueocean-dashboard:1.25.5
    - checks-api:1.7.4
    - pipeline-stage-view:2.24
    - ssh-credentials:1.19
    - popper2-api:2.11.5-2
    - structs:1.24
    - blueocean-core-js:1.25.5
    - momentjs:1.1.1
    - blueocean-personalization:1.25.5
    - sshd:3.1.0
    - git-client:3.11.0
    - workflow-durable-task-step:2.40
    - workflow-cps-global-lib-http:2.0.0
    - popper-api:1.16.1-3
    - workflow-basic-steps:2.24
    - pipeline-graph-analysis:1.12
    - blueocean-pipeline-editor:1.25.5
    - workflow-aggregator:2.7
    - plain-credentials:1.8
    - kubernetes-credentials:0.9.0
    - favorite:2.4.1
    - blueocean-i18n:1.25.5
    - workflow-support:3.8
    - github:1.34.3
    - configuration-as-code:1.55.1
    - display-url-api:2.3.6
    - blueocean-config:1.25.5
    - jenkins-design-language:1.25.5
    - bootstrap4-api:4.6.0-5
    - bouncycastle-api:2.26
    - durable-task:1.39
    - blueocean-git-pipeline:1.25.5
    - font-awesome-api:6.1.1-1
    - caffeine-api:2.9.3-65.v6a_47d0f4d1fe
    - jackson2-api:2.13.3-285.vc03c0256d517
    - htmlpublisher:1.30
    - workflow-api:1164.v760c223ddb_32
    - pipeline-stage-step:293.v200037eefcd5
    - git:4.11.3
    - workflow-job:1186.v8def1a_5f3944
    - blueocean-pipeline-scm-api:1.25.5
    - pipeline-stage-tags-metadata:2.2086.v12b_420f036e5
    - jira:3.7.1
    - matrix-project:771.v574584b_39e60
    - jsch:0.1.55.2
    - lockable-resources:2.15
    - variant:1.4
    - git-server:1.11
    - cloudbees-bitbucket-branch-source:773.v4b_9b_005b_562b_
    - trilead-api:1.57.v6e90e07157e1
    - scm-api:608.vfa_f971c5a_a_e9
    - docker-workflow:1.28
    - pubsub-light:1.16
    - jdk-tool:1.5
    - branch-api:2.1046.v0ca_37783ecc5
    - plugin-util-api:2.17.0
    - authentication-tokens:1.4
    - handlebars:3.0.8
    - pipeline-model-extensions:2.2086.v12b_420f036e5
    - token-macro:293.v283932a_0a_b_49
    - pipeline-rest-api:2.24
    - blueocean-display-url:2.4.1
    - jjwt-api:0.11.5-77.v646c772fddb_0
    - mailer:414.vcc4c33714601
    - blueocean-autofavorite:1.2.5
    - blueocean-commons:1.25.5
    - blueocean:1.25.5
    - command-launcher:84.v4a_97f2027398
    - blueocean-rest:1.25.5
    - kubernetes:3651.v908e7db_10d06
    - apache-httpcomponents-client-4-api:4.5.13-1.0
    - cloudbees-folder:6.729.v2b_9d1a_74d673
    - job-dsl:1.79
    - blueocean-bitbucket-pipeline:1.25.5
    - docker-commons:1.19
    - bootstrap5-api:5.1.3-7
    - blueocean-jira:1.25.5
    - pipeline-milestone-step:101.vd572fef9d926
    - blueocean-pipeline-api-impl:1.25.5
    - blueocean-github-pipeline:1.25.5
    - pipeline-model-api:2.2086.v12b_420f036e5
    - pipeline-model-definition:2.2086.v12b_420f036e5
    - echarts-api:5.3.2-3
    - docker-custom-build-environment:1.7.3
    - handy-uri-templates-2-api:2.1.8-22.v77d5b_75e6953
    - kubernetes-client-api:5.12.2-193.v26a_6078f65a_9
    - github-branch-source:1637.vd833b_7ca_7654
    - blueocean-jwt:1.25.5
    - pipeline-input-step:448.v37cea_9a_10a_70
    - github-api:1.303-400.v35c2d8258028
    - junit:1119.va_a_5e9068da_d7
    - credentials-binding:523.vd859a_4b_122e6
    - workflow-scm-step:400.v6b_89a_1317c9a_
    - pipeline-build-step:2.18
    - ace-editor:1.1
    - blueocean-web:1.25.5
    - workflow-step-api:625.vd896b_f445a_f8
    - sse-gateway:1.25
    - credentials:credentials:1129.vef26f5df883c
    - okhttp-api:okhttp-api:4.9.3-105.vb96869f8ac3a
    - snakeyaml-api:1.30.1
    - blueocean-rest-impl:1.25.5
    - metrics:4.1.6.2
    - blueocean-events:1.25.5
    - workflow-cps:2725.v7b_c717eb_12ce
    - jquery3-api:3.6.0-4
    - script-security:1175.v4b_d517d6db_f0
    - workflow-multibranch:716.vc692a_e52371b_
  JCasC:
    enabled: true
    configScripts:
      cloud: |
        jenkins:
            clouds:
                - kubernetes:
                    name: "gke-executors"
                    serverUrl: "https://kubernetes.default"
                    jenkinsTunnel: "jenkins-agent:50000"
                    jenkinsUrl: "http://jenkins:80"
                    skipTlsVerify: true
                    namespace: "default"
                    templates:
                        - name: "jenkins-jnlp"
                          namespace: "default"
                          nodeUsageMode: NORMAL
                          label: "jnlp-exec"
                          containers:
                            - name: "jnlp"
                              image: "jenkins/jnlp-slave"
                              alwaysPullImage: false
                              workingDir: "/home/jenkins/agent"
                              ttyEnabled: true
                              command: ""
                              args: ""
                              resourceRequestCpu: "500m"
                              resourceLimitCpu: "500m"
                              resourceRequestMemory: "1Gi"
                              resourceLimitMemory: "1Gi"
                          volumes:
                            - emptyDirVolume:
                                memory: false
                                mountPath: "/tmp"
                          idleMinutes: "1"
                          activeDeadlineSeconds: "120"
                          slaveConnectTimeout: "1000"
                        - name: "terraform"
                          namespace: "default"
                          nodeUsageMode: NORMAL
                          serviceAccount: ${jenkins_tf_ksa}
                          label: "terraform-exec"
                          containers:
                            - name: "terraform"
                              image: "hashicorp/terraform:0.12.29"
                              alwaysPullImage: false
                              workingDir: "/home/jenkins/agent"
                              ttyEnabled: true
                              command: "/bin/sh -c"
                              args: "cat"
                              resourceRequestCpu: "100m"
                              resourceLimitCpu: "500m"
                              resourceRequestMemory: "500Mi"
                              resourceLimitMemory: "1Gi"
                          volumes:
                            - emptyDirVolume:
                                memory: false
                                mountPath: "/tmp"
                          podRetention: "never"
                          activeDeadlineSeconds: "300"
                          slaveConnectTimeout: "1000"
      credentials: |
        credentials:
            system:
                domainCredentials:
                - credentials:
                    - usernamePassword:
                        scope: GLOBAL
                        id: "github-token"
                        username: ${GITHUB_USERNAME}
                        password: ${GITHUB_TOKEN}
                        description: "Github personal token"
