controller:
  servicePort: 80
  serviceType: LoadBalancer
  installPlugins:
    - kubernetes:latest
    - workflow-job:latest
    - workflow-aggregator:latest
    - credentials-binding:latest
    - git:latest
    - google-kubernetes-engine:latest
    - configuration-as-code:latest
    - blueocean:latest
    - docker-plugin:latest
    - docker-workflow:latest
    - theme-manager:latest
  resources:
    requests:
      cpu: "50m"
      memory: "1024Mi"
    limits:
      cpu: "1"
      memory: "3500Mi"
  javaOpts: "-Xms3500m -Xmx3500m"
agent:
  resources:
    requests:
      cpu: "500m"
      memory: "512Mi"
    limits:
      cpu: "1"
      memory: "1024Mi"
  JCasC:
    enabled: true
    configScripts:
      cloud: |
        jenkins:
            clouds:
                - kubernetes:
                    name: "gke-executors"
                    serverUrl: "https://kubernetes.default"
                    jenkinsTunnel: "jenkins-agent:50000"
                    jenkinsUrl: "http://jenkins:80"
                    skipTlsVerify: true
                    namespace: "default"
                    templates:
                        - name: "jenkins-jnlp"
                          namespace: "default"
                          nodeUsageMode: NORMAL
                          label: "jnlp-exec"
                          containers:
                            - name: "jnlp"
                              image: "jenkins/jnlp-slave"
                              alwaysPullImage: false
                              workingDir: "/home/jenkins/agent"
                              ttyEnabled: true
                              command: ""
                              args: ""
                              resourceRequestCpu: "500m"
                              resourceLimitCpu: "500m"
                              resourceRequestMemory: "1Gi"
                              resourceLimitMemory: "1Gi"
                          volumes:
                            - emptyDirVolume:
                                memory: false
                                mountPath: "/tmp"
                          idleMinutes: "1"
                          activeDeadlineSeconds: "120"
                          slaveConnectTimeout: "1000"
                        - name: "terraform"
                          namespace: "default"
                          nodeUsageMode: NORMAL
                          serviceAccount: ${jenkins_tf_ksa}
                          label: "terraform-exec"
                          containers:
                            - name: "terraform"
                              image: "hashicorp/terraform:0.12.29"
                              alwaysPullImage: false
                              workingDir: "/home/jenkins/agent"
                              ttyEnabled: true
                              command: "/bin/sh -c"
                              args: "cat"
                              resourceRequestCpu: "100m"
                              resourceLimitCpu: "500m"
                              resourceRequestMemory: "500Mi"
                              resourceLimitMemory: "1Gi"
                          volumes:
                            - emptyDirVolume:
                                memory: false
                                mountPath: "/tmp"
                          podRetention: "never"
                          activeDeadlineSeconds: "300"
                          slaveConnectTimeout: "1000"
      credentials: |
        credentials:
            system:
                domainCredentials:
                - credentials:
                    - usernamePassword:
                        scope: GLOBAL
                        id: "github-token"
                        username: ${GITHUB_USERNAME}
                        password: ${GITHUB_TOKEN}
                        description: "Github personal token"
