apiVersion: v1
kind: ServiceAccount
metadata:
  name: deworg-catalogue
---
apiVersion: v1
kind: Service
metadata:
  name: deworg-catalogue
spec:
  selector:
    app: deworg-catalogue
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deworg-catalogue
  annotations:
    "consul.hashicorp.com/connect-inject": "true"
spec:
  selector:
    matchLabels:
      app: deworg-catalogue
  template:
    metadata:
      labels:
        app: deworg-catalogue
    spec:
      containers:
        - name: deworg-catalogue
          image: deworg/catalogue:0.1.0
          env:
            - name: CONSUL_HOST
              value: "consul-server.consul"
            - name: AUTH0_AUDIENCE
              valueFrom:
                configMapKeyRef:
                  name: auth0
                  key: audience
            - name: AUTH0_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: auth0
                  key: domain
          ports:
            - containerPort: 8080
